name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  CI:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y cmake
    - uses: actions/checkout@v3
    - name: Build
      run: cmake -S . -B build && cmake --build build
    - name: Set up Signer Proxy Binaries
      run: ./scripts/setup_signer_proxy.sh
    - name: Integration Test
      run: ./scripts/integration_test.sh

